### ISSUE TITLE
Issue when deployed on remote server?

### ISSUE THREAD

**Issue by jpatrickpark** [bryik/aframe-bmfont-text-component#15]
I am having an issue when I deploy it to a remote server through cloudflare using SSL.
So when I run the code on my local desktop then everything works as expected; I can run the pre-mode demo successfully.
However, if I deploy the same code on a remote ubuntu 14.04 server and open it using the same chrome browser on local desktop then just an empty screen with a VR button is displayed.
Curiously, if I view the same page on the remote server on my android device, everything works successfully.
I uploaded the code here https://apps.jpatrickpark.com/lsl/

These are the error messages I received on desktop chrome browser:

Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at s.init (https://aframe.io/releases/0.3.0/aframe.min.js:69:591)
    at s.updateProperties (https://aframe.io/releases/0.3.0/aframe.min.js:143:2661)
    at new s (https://aframe.io/releases/0.3.0/aframe.min.js:143:3586)
    at a-entity.value (https://aframe.io/releases/0.3.0/aframe.min.js:135:3855)
    at a-entity.value (https://aframe.io/releases/0.3.0/aframe.min.js:135:5048)
    at e (https://aframe.io/releases/0.3.0/aframe.min.js:135:4639)
    at Array.forEach (native)
    at a-entity.value (https://aframe.io/releases/0.3.0/aframe.min.js:135:4855)
    at t (https://aframe.io/releases/0.3.0/aframe.min.js:135:3097)
    at eval (https://aframe.io/releases/0.3.0/aframe.min.js:139:1196)
material.js:79

Uncaught (in promise) TypeError: Cannot read property 'removeBehavior' of null
    at s.updateBehavior (https://aframe.io/releases/0.3.0/aframe.min.js:87:1450)
    at s.updateSchema (https://aframe.io/releases/0.3.0/aframe.min.js:87:1141)
    at s.updateProperties (https://aframe.io/releases/0.3.0/aframe.min.js:143:2461)
    at new s (https://aframe.io/releases/0.3.0/aframe.min.js:143:3586)
    at a-entity.value (https://aframe.io/releases/0.3.0/aframe.min.js:135:3855)
    at a-entity.value (https://aframe.io/releases/0.3.0/aframe.min.js:135:5048)
    at e (https://aframe.io/releases/0.3.0/aframe.min.js:135:4639)
    at Array.forEach (native)
    at a-entity.value (https://aframe.io/releases/0.3.0/aframe.min.js:135:4855)
    at t (https://aframe.io/releases/0.3.0/aframe.min.js:135:3097)

Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at s.init (https://aframe.io/releases/0.3.0/aframe.min.js:69:591)
    at s.updateProperties (https://aframe.io/releases/0.3.0/aframe.min.js:143:2661)
    at new s (https://aframe.io/releases/0.3.0/aframe.min.js:143:3586)
    at a-entity.value (https://aframe.io/releases/0.3.0/aframe.min.js:135:3855)
    at a-entity.value (https://aframe.io/releases/0.3.0/aframe.min.js:135:5048)
    at a-entity.value (https://aframe.io/releases/0.3.0/aframe.min.js:135:5199)
    at a-entity.value (https://aframe.io/releases/0.3.0/aframe.min.js:135:6335)
    at r.setActiveCamera (https://aframe.io/releases/0.3.0/aframe.min.js:246:1589)
    at s.update (https://aframe.io/releases/0.3.0/aframe.min.js:69:982)
    at s.updateProperties (https://aframe.io/releases/0.3.0/aframe.min.js:143:2693)

**Comment by jpatrickpark** [comment]
Never mind; the problem was the use of rocketscript, an experimental feature of cloudflare. It is known to break some javascript code.
